sudo: required
dist: jammy
language: node_js
node_js:
  - '22.4.0'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm i -g npm@8.19.4
  - npm --version

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm install -g codecov
  - npm install -g codacy-coverage
  - npm ci

before_script:
  - export NODE_OPTIONS="--max-old-space-size=8192"

script:
  - npm run build-lib
  - npm run build-showcase
  - npm run test-ci

before_deploy: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm -rf systelab.github.io/virtual-keyboard/*
    cp -r dist/systelab-virtual-keyboard/* systelab.github.io/virtual-keyboard
    sed -i -e "s~base href=\"/\"~base href=\"/virtual-keyboard/\"~g" ./systelab.github.io/virtual-keyboard/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
    cd ..
  fi
  cd dist/systelab-virtual-keyboard

deploy:
  skip_cleanup: true
  provider: npm
  edge:
    branch: v2.0.3-beta.5
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  on:
    tags: true
